// [payment_intent.succeeded]
const paymentIntentSucceeded = {
  id: 'pi_3Pnx3FJQMax7OQEN1WEfG7vX',
  object: 'payment_intent',
  amount: 250,
  amount_capturable: 0,
  amount_details: { tip: {} },
  amount_received: 250,
  application: null,
  application_fee_amount: null,
  automatic_payment_methods: null,
  canceled_at: null,
  cancellation_reason: null,
  capture_method: 'automatic_async',
  charges: {
    object: 'list',
    data: [
      {
        id: 'py_3Pnx3FJQMax7OQEN1CCfJuux',
        object: 'charge',
        amount: 250,
        amount_captured: 250,
        amount_refunded: 0,
        application: null,
        application_fee: null,
        application_fee_amount: null,
        balance_transaction: null,
        billing_details: {
          address: {
            city: null,
            country: 'ID',
            line1: null,
            line2: null,
            postal_code: null,
            state: null,
          },
          email: 'fazufi10@gmail.com',
          name: 'fazufi',
          phone: null,
        },
        calculated_statement_descriptor: null,
        captured: true,
        created: 1723702851,
        currency: 'usd',
        customer: 'cus_QbTLO7CtNDsj6Y',
        description: null,
        destination: null,
        dispute: null,
        disputed: false,
        failure_balance_transaction: null,
        failure_code: null,
        failure_message: null,
        fraud_details: {},
        invoice: null,
        livemode: false,
        metadata: {},
        on_behalf_of: null,
        order: null,
        outcome: {
          network_status: 'approved_by_network',
          reason: null,
          risk_level: 'normal',
          risk_score: 16,
          seller_message: 'Payment complete.',
          type: 'authorized',
        },
        paid: true,
        payment_intent: 'pi_3Pnx3FJQMax7OQEN1WEfG7vX',
        payment_method: 'pm_1Pnx3EJQMax7OQENbkwVUSxG',
        payment_method_details: { link: { country: 'US' }, type: 'link' },
        radar_options: {},
        receipt_email: null,
        receipt_number: null,
        receipt_url:
          'https://pay.stripe.com/receipts/payment/CAcaFwoVYWNjdF8xRXFFWHpKUU1heDdPUUVOKMS89rUGMga5NRLkaN46LBYbpqZGdSY_BgEGcCQpexBMtVNB_f3LTX2YeCO1m0LjZtu5gNxvw7ieG5ft',
        refunded: false,
        refunds: {
          object: 'list',
          data: [],
          has_more: false,
          total_count: 0,
          url: '/v1/charges/py_3Pnx3FJQMax7OQEN1CCfJuux/refunds',
        },
        review: null,
        shipping: null,
        source: null,
        source_transfer: null,
        statement_descriptor: null,
        statement_descriptor_suffix: null,
        status: 'succeeded',
        transfer_data: null,
        transfer_group: null,
      },
    ],
    has_more: false,
    total_count: 1,
    url: '/v1/charges?payment_intent=pi_3Pnx3FJQMax7OQEN1WEfG7vX',
  },
  client_secret: 'pi_3Pnx3FJQMax7OQEN1WEfG7vX_secret_6Dy94KU4Ln51zC8JDVHzy8NHU',
  confirmation_method: 'automatic',
  created: 1723702849,
  currency: 'usd',
  customer: 'cus_QbTLO7CtNDsj6Y',
  description: null,
  invoice: null,
  last_payment_error: null,
  latest_charge: 'py_3Pnx3FJQMax7OQEN1CCfJuux',
  livemode: false,
  metadata: {},
  next_action: null,
  on_behalf_of: null,
  payment_method: 'pm_1Pnx3EJQMax7OQENbkwVUSxG',
  payment_method_configuration_details: null,
  payment_method_options: { link: { persistent_token: null } },
  payment_method_types: ['link'],
  processing: null,
  receipt_email: null,
  review: null,
  setup_future_usage: null,
  shipping: null,
  source: null,
  statement_descriptor: null,
  statement_descriptor_suffix: null,
  status: 'succeeded',
  transfer_data: null,
  transfer_group: null,
};

// [payment_intent.created]
const paymentIntentCreated = {
  id: 'pi_3Pnx3FJQMax7OQEN1WEfG7vX',
  object: 'payment_intent',
  amount: 250,
  amount_capturable: 0,
  amount_details: { tip: {} },
  amount_received: 0,
  application: null,
  application_fee_amount: null,
  automatic_payment_methods: null,
  canceled_at: null,
  cancellation_reason: null,
  capture_method: 'automatic_async',
  charges: {
    object: 'list',
    data: [],
    has_more: false,
    total_count: 0,
    url: '/v1/charges?payment_intent=pi_3Pnx3FJQMax7OQEN1WEfG7vX',
  },
  client_secret: 'pi_3Pnx3FJQMax7OQEN1WEfG7vX_secret_6Dy94KU4Ln51zC8JDVHzy8NHU',
  confirmation_method: 'automatic',
  created: 1723702849,
  currency: 'usd',
  customer: 'cus_QbTLO7CtNDsj6Y',
  description: null,
  invoice: null,
  last_payment_error: null,
  latest_charge: null,
  livemode: false,
  metadata: {},
  next_action: null,
  on_behalf_of: null,
  payment_method: null,
  payment_method_configuration_details: null,
  payment_method_options: { link: { persistent_token: null } },
  payment_method_types: ['link'],
  processing: null,
  receipt_email: null,
  review: null,
  setup_future_usage: null,
  shipping: null,
  source: null,
  statement_descriptor: null,
  statement_descriptor_suffix: null,
  status: 'requires_payment_method',
  transfer_data: null,
  transfer_group: null,
};

// CHECKOUT_SESSION_COMPLETED
const CHECKOUT_SESSION_COMPLETED = {
  id: 'cs_test_a1meBVqPNUj7QjfSkQdzbbRrqAaiPSOySKLov5xsoaTaO5Gf2EEWLzH2a1',
  object: 'checkout.session',
  after_expiration: null,
  allow_promotion_codes: null,
  amount_subtotal: 250,
  amount_total: 250,
  automatic_tax: { enabled: false, liability: null, status: null },
  billing_address_collection: 'auto',
  cancel_url: null,
  client_reference_id: null,
  client_secret: null,
  consent: null,
  consent_collection: null,
  created: 1723702843,
  currency: 'usd',
  currency_conversion: null,
  custom_fields: [],
  custom_text: {
    after_submit: null,
    shipping_address: null,
    submit: null,
    terms_of_service_acceptance: null,
  },
  customer: 'cus_QbTLO7CtNDsj6Y',
  customer_creation: null,
  customer_details: {
    address: {
      city: null,
      country: 'ID',
      line1: null,
      line2: null,
      postal_code: null,
      state: null,
    },
    email: 'fazufi10@gmail.com',
    name: 'INI ADALAH CARD HOLDER',
    phone: null,
    tax_exempt: 'none',
    tax_ids: [],
  },
  customer_email: null,
  expires_at: 1723789243,
  invoice: 'in_1Pnx3IJQMax7OQENDbaIOS0r',
  invoice_creation: {
    enabled: true,
    invoice_data: {
      account_tax_ids: null,
      custom_fields: null,
      description: null,
      footer: null,
      issuer: { type: 'self' },
      metadata: {},
      rendering_options: null,
    },
  },
  livemode: false,
  locale: null,
  metadata: {
    user_id: 'clztx6a1i0001h0uxu5jzp4i3',
    email: 'fazufi10@gmail.com',
    order_id: 'clzukrvnk0003h0uxpsd1wsu1',
    discount: '0',
    amount: '2.5',
    total: '2.5',
  },
  mode: 'payment',
  payment_intent: 'pi_3Pnx3FJQMax7OQEN1WEfG7vX',
  payment_link: null,
  payment_method_collection: 'if_required',
  payment_method_configuration_details: {
    id: 'pmc_1OL1VjJQMax7OQENz0NEfel7',
    parent: null,
  },
  payment_method_options: {},
  payment_method_types: ['card', 'link'],
  payment_status: 'paid',
  phone_number_collection: { enabled: false },
  recovered_from: null,
  redirect_on_completion: 'always',
  return_url: 'http://localhost:3045/orders',
  saved_payment_method_options: {
    allow_redisplay_filters: ['always'],
    payment_method_remove: null,
    payment_method_save: null,
  },
  setup_intent: null,
  shipping: null,
  shipping_address_collection: null,
  shipping_options: [],
  shipping_rate: null,
  status: 'complete',
  submit_type: null,
  subscription: null,
  success_url: null,
  total_details: { amount_discount: 0, amount_shipping: 0, amount_tax: 0 },
  ui_mode: 'embedded',
  url: null,
};

const customer_search = {
  data: [
    {
      id: 'cus_QbTLO7CtNDsj6Y',
      object: 'customer',
      address: {
        city: null,
        country: 'ID',
        line1: null,
        line2: null,
        postal_code: null,
        state: null,
      },
      balance: 0,
      created: 1722823885,
      currency: 'usd',
      default_source: null,
      delinquent: true,
      description: null,
      discount: null,
      email: 'fazufi10@gmail.com',
      invoice_prefix: '1E206F49',
      invoice_settings: {
        custom_fields: null,
        default_payment_method: null,
        footer: null,
        rendering_options: null,
      },
      livemode: false,
      metadata: {},
      name: 'INI ADALAH CARD HOLDER',
      next_invoice_sequence: 3,
      phone: null,
      preferred_locales: ['en-US'],
      shipping: null,
      tax_exempt: 'none',
      test_clock: null,
    },
  ],
};

const invoice = {
  id: 'in_1PnxGuJQMax7OQENrzfiORAI',
  object: 'invoice',
  account_country: 'AU',
  account_name: 'URBAN THAI ENMORE 2042',
  account_tax_ids: null,
  amount_due: 250,
  amount_paid: 250,
  amount_remaining: 0,
  amount_shipping: 0,
  application: null,
  application_fee_amount: null,
  attempt_count: 1,
  attempted: true,
  auto_advance: false,
  automatic_tax: { enabled: false, liability: null, status: null },
  automatically_finalizes_at: null,
  billing_reason: 'manual',
  charge: 'py_3PnxGsJQMax7OQEN0fCKrWNA',
  collection_method: 'send_invoice',
  created: 1723703695,
  currency: 'usd',
  custom_fields: null,
  customer: 'cus_QbTLO7CtNDsj6Y',
  customer_address: {
    city: null,
    country: 'ID',
    line1: null,
    line2: null,
    postal_code: null,
    state: null,
  },
  customer_email: 'fazufi10@gmail.com',
  customer_name: 'INI ADALAH CARD HOLDER',
  customer_phone: null,
  customer_shipping: null,
  customer_tax_exempt: 'none',
  customer_tax_ids: [],
  default_payment_method: null,
  default_source: null,
  default_tax_rates: [],
  description: null,
  discount: null,
  discounts: [],
  due_date: 1723703695,
  effective_at: 1723703695,
  ending_balance: 0,
  footer: null,
  from_invoice: null,
  hosted_invoice_url:
    'https://invoice.stripe.com/i/acct_1EqEXzJQMax7OQEN/test_YWNjdF8xRXFFWHpKUU1heDdPUUVOLF9RZkhxVVpLdTJvQjNMdWZGbDA4Rmp1dGJMY0xZckQ0LDExNDI0NDQ5OQ0200bN9C0Ikn?s=ap',
  invoice_pdf:
    'https://pay.stripe.com/invoice/acct_1EqEXzJQMax7OQEN/test_YWNjdF8xRXFFWHpKUU1heDdPUUVOLF9RZkhxVVpLdTJvQjNMdWZGbDA4Rmp1dGJMY0xZckQ0LDExNDI0NDQ5OQ0200bN9C0Ikn/pdf?s=ap',
  issuer: { type: 'self' },
  last_finalization_error: null,
  latest_revision: null,
  lines: {
    object: 'list',
    data: [[Object]],
    has_more: false,
    total_count: 1,
    url: '/v1/invoices/in_1PnxGuJQMax7OQENrzfiORAI/lines',
  },
  livemode: false,
  metadata: {},
  next_payment_attempt: null,
  number: '1E206F49-0005',
  on_behalf_of: null,
  paid: true,
  paid_out_of_band: false,
  payment_intent: 'pi_3PnxGsJQMax7OQEN0oS6QfKH',
  payment_settings: {
    default_mandate: null,
    payment_method_options: null,
    payment_method_types: null,
  },
  period_end: 1723703695,
  period_start: 1723703695,
  post_payment_credit_notes_amount: 0,
  pre_payment_credit_notes_amount: 0,
  quote: null,
  receipt_number: null,
  rendering: { amount_tax_display: null, pdf: { page_size: 'letter' } },
  shipping_cost: null,
  shipping_details: null,
  starting_balance: 0,
  statement_descriptor: null,
  status: 'paid',
  status_transitions: {
    finalized_at: 1723703695,
    marked_uncollectible_at: null,
    paid_at: 1723703695,
    voided_at: null,
  },
  subscription: null,
  subscription_details: { metadata: null },
  subtotal: 250,
  subtotal_excluding_tax: 250,
  tax: null,
  test_clock: null,
  total: 250,
  total_discount_amounts: [],
  total_excluding_tax: 250,
  total_tax_amounts: [],
  transfer_data: null,
  webhooks_delivered_at: 1723703699,
};
